### ISSUE TITLE
Channel Website Revisions

### ISSUE THREAD

**Issue by cr5315** [dogecoinirc/forum#1]
* IRC Nickname: cr5315

The current website (hosted [here](http://cr5315.com/dogecoinirc/)) is a bit outdated. Most of the Dogecoin related links are broken (service no longer exists).

It might also be a good idea to start hosting the website through this organization, which would change the URL to dogecoinirc.github.io, rather than cr5315.com/dogecoinirc. Using that method, we could use a page generator such as Jekyll to simplify some aspects of updating the website.

**Comment by sh0lla** [comment]
+1
